branches:
  - name: master
  - name: next
    channel: next

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/npm'
    - pkgRoot: 'dist/angular-morris-js'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
      message: "chore(release): version ${nextRelease.version}\n\n[skip ci]\n\n${nextRelease.notes}"
  - '@semantic-release/github'

preset: angular
