language: node_js
node_js:
  - lts/*
dist: trusty
os: linux

env:
  global:
    - TMPDIR=/tmp

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

script:
  - commitlint-travis
  - yarn prettier:check
  - ng lint angular-morris-js
  - ng build angular-morris-js --prod
  - ng lint angular-morris-js-demo
  - ng build angular-morris-js-demo --prod --base-href="/angular-morris-js/$([ "$TRAVIS_PULL_REQUEST" != false ] && echo "pulls/$TRAVIS_PULL_REQUEST/" || echo "branches/$TRAVIS_BRANCH/")"
  # - xvfb-run npm run e2e

after_success:
  - bash scripts/travis-gh-pages.sh $TMPDIR/gh-pages $TRAVIS_BUILD_DIR/dist/angular-morris-js-demo

before_install:
  - npm install -g yarn

before_deploy:
  - ng build angular-morris-js --prod

deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    all_branches: true
